# antigen 
source ~/dotfile/config/zsh/antigen.zsh

# packages
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions
# antigen bundle docker
antigen bundle yarn
antigen bundle tmux
antigen bundle thewtex/tmux-mem-cpu-load
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle babarot/enhancd

antigen theme clean

antigen apply

# aliases
alias ls="lsd"
alias grep="grep --color=auto"
alias cat=batcat
alias ls=lsd

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#6c6c6c,bold'
ENHANCD_FILTER="fzf --height 40%:fzy"
ZSH_TMUX_AUTOSTART=true

# This loads nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"